#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);

//buat akun
// D:\Lp3i\LP3IKARAWANG>php create_users.php
// User Admin berhasil dibuat:
// Email: admin@gmail.com
// Password: 123456

// User Marketing berhasil dibuat:
// Email: marketing@gmail.com
// Password: 123456